lib/push_web/router.ex
defmodule PushWeb.Router do
  use PushWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  import PushWeb.Plugs.Authentication
  import PushWeb.Plugs.GettingStarted
  import PushWeb.Plugs.FetchCurrentApplication

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :authenticate_user
    plug :fetch_current_application
    plug :redirect_to_getting_started_if_required

    plug :put_layout, {PushWeb.LayoutView, :logged_in}
  end

  scope "/", PushWeb do
    pipe_through :browser # Use the default browser stack
    # Add public routes below.
    get "/", StaticPageController, :home

    resources "/sessions", SessionController, only: [:new, :create]
    delete "/signout", SessionController, :delete

    resources "/registrations", RegistrationController, only: [:new, :create]
  end

  scope "/", PushWeb do
    pipe_through :protected

    resources "/users", UserController
    resources "/dashboard", DashboardController, only: [:index]
    resources "/push_notifications", PushNotificationController, only: [:new, :create]
    resources "/confirmation", ConfirmationController, only: [:create, :show]
    resources "/getting_started", GettingStartedController, only: [:index, :create]
  end

  scope "/push_application", PushWeb do
    pipe_through :protected

    resources "/platforms", PlatformController, only: [:index, :new, :create]

    get "/keys", PushApplicationController, :keys
    resources "/", PushApplicationController
  end

  #################################################################################
  # API routes
  #################################################################################
  pipeline :api do
    plug :accepts, ["json"]
    plug BasicAuth, callback: &Push.PushApplications.find_by_key_and_secret/3
  end


  scope "/api/v1", PushWeb.API.V1, as: :api_v1 do
    pipe_through :api

    resources "/push_notifications", PushNotificationController, only: [:create]
  end
end

lib/push_web/views/layout_view.ex
defmodule PushWeb.LayoutView do
  use PushWeb, :view
end

lib/push_web/templates/layout/account_activation.html.eex
<%= if @conn.assigns.current_user.confirmed_at === nil do %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert border border-warning activateAccount" role="alert">
        <span class="activateAccount__message">You must confirm your account before you can use it in production.</span>
        <%= link to: confirmation_path(@conn, :create), method: :post, class: "activateAccount__activateLink pull-right" do %>
          Send confirmation email
        <% end %>
      </div>
    </div>
  </div>

  <% end %>

lib/push_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Push Horse</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <main role="main">
      <div class="container">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/push_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html>
  <head>
    <title>Confirm Your Email <Address></Address></title>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

lib/push_web/templates/layout/flash.html.eex
<%= if get_flash(@conn, :info) do %>
<div class="alert alert-success" role="alert">
  <%= get_flash(@conn, :info) %>
</div>
<% end %>

<%= if get_flash(@conn, :error) do %>
  <div class="ui negative message">
    <i class="close icon"></i>
    <div class="header">
      Error
    </div>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  </div>
<% end %>

lib/push_web/templates/layout/logged_in.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Push Horse</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <main role="main">
      <%= render "navigation.html", conn: @conn %>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <br/>
            <%= render "flash.html", conn: @conn %>
            <%= render "account_activation.html", conn: @conn %>
            <%= render @view_module, @view_template, assigns %>
          </div>
        </div>
      </div>
      </div>
    </main>

    <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/push_web/templates/layout/navigation.html.eex
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #2c3e50">

  <%= link to: dashboard_path(@conn, :index), class: "navbar-brand" do %>
    <%# <i class="fa fa-home fa-fw" aria-hidden="true"></i> %>
    Home
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link to: platform_path(@conn, :index), class: "nav-link #{ if @conn.request_path == platform_path(@conn, :index), do: 'active', else: nil }" do %>
        <%# <i class="fa fa-mobile fa-fw" aria-hidden="true"></i> %>
        Platforms
        <% end %>
      </li>
      <li class="nav-item">
        <%= link to: push_notification_path(@conn, :new), class: "nav-link #{ if @conn.request_path == push_notification_path(@conn, :new), do: 'active', else: nil }" do %>
        <%# <i class="fa fa-envelope-o fa-fw" aria-hidden="true"></i> %>
        Messages
        <% end %>
      </li>
      <br/>
      <li class="nav-item">
        <%= link to: push_application_path(@conn, :keys), class: "nav-link #{ if @conn.request_path == push_application_path(@conn, :keys), do: 'active', else: nil }" do %>
        <%# <i class="fa fa-terminal fa-fw" aria-hidden="true"></i> %>
        API
        <% end %>
      </li>
      <li class="nav-item">
        <%= link to: '#', class: "nav-link #{ if @conn.request_path == 'fake_path', do: 'active', else: nil }" do %>
        <%# <i class="fa fa-life-ring fa-fw" aria-hidden="true"></i> %>
        Events & logs
        <% end %>
      </li>
      <br/>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">
          <i class="fa fa-toggle-on fa-fw" aria-hidden="true"></i>
          Viewing test data
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fa fa-user" aria-hidden="true"></i></a>
      </li>
      <li class="nav-item">
        <%= link "Log out", to: session_path(@conn, :delete), method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

<nav class="nav subNav">
  <a class="nav-link active" href="#">Active</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link disabled" href="#">Disabled</a>
</nav>